//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CofcoInd.Areas.BackOffice
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoriasNotes
    {
        public int IdCategoriasNotes { get; set; }
        public string descCategoriasNotes { get; set; }
        public System.DateTime create_datetime { get; set; }
        public Nullable<System.DateTime> update_datetime { get; set; }
    }
}
