//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CofcoInd.Areas.BackOffice
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consultas
    {
        public int IdConsulta { get; set; }
        public string NombreConsulta { get; set; }
        public string EmailConsulta { get; set; }
        public string contenidoConsulta { get; set; }
        public System.DateTime create_datetime { get; set; }
        public Nullable<System.DateTime> update_datetime { get; set; }
        public string cuitConsulta { get; set; }
        public string domicilioConsulta { get; set; }
        public string residenciaConsulta { get; set; }
        public string cpConsulta { get; set; }
        public string telefonoConsulta { get; set; }
        public string ocupacionConsulta { get; set; }
        public string sexoConsulta { get; set; }
        public string provinciaConsulta { get; set; }
        public string localidadConsulta { get; set; }
        public string apellidoConsulta { get; set; }
    }
}
