//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNV_Site.Areas.BackOffice
{
    using System;
    using System.Collections.Generic;
    
    public partial class RespuestaConsultas
    {
        public int IdRespuestaConsultas { get; set; }
        public int IdConsulta { get; set; }
        public string NombreRespuestaConsultas { get; set; }
        public string contenidoConsulta { get; set; }
        public System.DateTime create_datetime { get; set; }
        public Nullable<System.DateTime> update_datetime { get; set; }
    }
}
