//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNV_Site.Areas.BackOffice
{
    using System;
    using System.Collections.Generic;
    
    public partial class SettingsIntegrationNotes
    {
        public int IdSettingsIntegrationNotes { get; set; }
        public string descSettingsIntegrationNotes { get; set; }
        public string keySettingsIntegrationNotes { get; set; }
        public string valueSettingsIntegrationNotes { get; set; }
        public System.DateTime create_datetime { get; set; }
        public Nullable<System.DateTime> update_datetime { get; set; }
        public bool ActiveSettingsIntegrationNotes { get; set; }
    }
}
